Repository telus/tds-core, pull requests merged in 2018-07, with the labels that each got.

#660 chore(dependencies): patch some dependencies
  package.json
  yarn.lock
Labels: priority: low, status: review needed, type: enhancement

#659 chore(github): add recreateClosed option for Renovate to retry upgrades
  renovate.json
Labels: priority: low, status: review needed, type: discussion

#678 fix(core-expand-collapse): enable adaptive panel size
  packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
  packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
  packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
  shared/components/Animation/Reveal.jsx
  shared/components/Animation/__tests__/__snapshots__/Reveal.spec.jsx.snap
Labels: priority: high, status: review needed, type: defect

#684 fix(core-expand-collapse): wrap header tags around correct element
  e2e/output/components/ExpandCollapse/baseline/chrome_headless.png
  packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
  packages/ExpandCollapse/__tests__/ExpandCollapse.spec.jsx
  packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
Labels: accessibility, priority: critical, status: review needed, type: defect
